openapi: 3.0.3
info:
  version: 1.0.0
  title: organization management api service
  description: ''
  termsOfService: ''
  contact: {}
  license:
    name: 'MIT'
servers:
  - url: http://organization.local:8010/api/v1
  - url: http://localhost:8000/api/v1
  - url: http://localhost:8002/api/v1
  - url: https://api.bus.softbd.xyz/org/api/v1
  - url: http://nise3-organization.asm/api/v1
paths:
  /organization-registration:
    post:
      summary: Register Organization
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/organizationRegister'
      responses:
        '200':
          description: Register an organization
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organizationRegister'
              example:
                data:
                  id: 1
                  title_en: Roob-Stanton
                  title: Roob-Stanton
                  organization_type_id: 1
                  email: jadyn05@osinski.biz
                  mobile: '01758393749'
                  name_of_the_office_head: Roob-Stanton
                  name_of_the_office_head_designation: Chairman
                  address: |-
                    97645 Roxanne Stream
                     West Cleorashire, UT 17550-13...
                  contact_person_name: Roob-Stanton
                  contact_person_designation: Chairman
                  contact_person_email: jadyn05@osinski.biz
                  contact_person_mobile: '01758393749'
                  password: '12345678'
                  password_confirmation: '12345678'
                _response_status:
                  success: true
                  code: 200
                  query_time: 1 second before
      tags:
        - Organization Registration
components:
  schemas:
    organizationRegister:
      type: object
      description: Organization Registration
      properties:
        title_en:
          type: string
          description: title in English
          minLength: 2
          maxLength: 300
        title:
          type: string
          description: ' title in Bengali'
          minLength: 2
          maxLength: 1000
        organization_type_id:
          type: integer
          description: Organization type id
        email:
          type: string
          description: email address
        mobile:
          type: string
          description: Mobile number of organization
        contact_person_mobile:
          type: string
          description: Contact person mobile number
        name_of_the_office_head:
          type: string
          description: Head of office
        name_of_the_office_head_en:
          type: string
          description: Head of office
        name_of_the_office_head_designation:
          type: string
          description: 'Head of office Designation '
        name_of_the_office_head_designation_en:
          type: string
          description: 'Head of office Designation '
        contact_person_name:
          type: string
          description: Contact person name
        contact_person_name_en:
          type: string
          description: Contact person name
        contact_person_designation:
          type: string
          description: Contact person's designation
        contact_person_designation_en:
          type: string
          description: Contact person's designation
        contact_person_email:
          type: string
          description: Contact person email address
        address:
          type: string
          maximum: 1000
          minimum: 2
          description: organization address
        address_en:
          type: string
          maximum: 1000
          minimum: 2
          description: organization address
        password:
          type: string
          format: password
        password_confirmation:
          type: string
          format: password
      required:
        - title_en
        - title
        - organization_type_id
        - email
        - mobile
        - contact_person_mobile
        - name_of_the_office_head
        - contact_person_name
        - contact_person_designation
        - contact_person_designation_en
        - contact_person_email
        - address
        - address_en
        - password
        - password_confirmation
