# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Please do not change anything if you dont know what you are doing - Kalyan

variables:

  hostName: org.bus.softbd.xyz

  # app version, changing version will auto deploy the app to current version

  imageAppVersion: "1.0.26"

  # increase this when you need scale up
  replicaCount: 1

  imagePullPolicy: IfNotPresent

  serviceType: ClusterIP

  # service port, this provide traffic to ingress within this port
  servicePort: 80

  # target container port
  serviceTargetPort: 80

  #app buil image
  #imageRepository: registry.bus-staging.softbdltd.com/nise3-organization-management-api-service
  imageRepository: rhysha/nise3-organization-management-api-service

  #auto scaling config
  #autoScalingEnabled: 0

  #autoScalingMinReplicas: 1

  #autoScalingMaxReplicas: 100

  #autoScalingTargetCPUUtilizationPercentage: 80

  #autoScalingTargetMemoryUtilizationPercentage: 80


  # application config

  APP_ENV: "local"
  APP_DEBUG: "false"
  APP_URL: "org.bus.softbd.xyz"
  DB_HOST: 172.17.177.79
  DB_PORT: "3306"
  DB_DATABASE: org_manage
  DB_USERNAME: n3_org
  DB_PASSWORD: "kvx5V3Y^7"


  #control git realese branch
  GIT_DEVELOPMENT_BRANCH: "develop"
  GIT_PRODUCTION_BRANCH: "master"
